[build]
  functions = "netlify/functions"
  publish   = "public"

[dev]
  functions = "netlify/functions"

  [build]
  publish = "public"

[[edge_functions]]
  path = "/portal/*"
  function = "protect-portal"

